// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-reports.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_reports_default = defineTool({
  name: "list_reports",
  title: "List my analyses",
  description: "List the signed-in user's Concept AI feasibility analyses (title, industry, status, verdict, share slug, created date). Newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum number of analyses to return (1-50)."),
    includeArchived: z.boolean().default(false).describe("Include soft-archived analyses.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, includeArchived }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    let q = client(ctx).from("reports").select("id, display_id, title, industry, status, slug, is_public, created_at, updated_at, archived_at").order("created_at", { ascending: false }).limit(limit);
    if (!includeArchived) q = q.is("archived_at", null);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { reports: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-report.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_report_default = defineTool2({
  name: "get_report",
  title: "Get analysis",
  description: "Return a full Concept AI feasibility analysis (inputs, canonical report output, FMART-O scores, verdict, evidence) by report id, display id, or share slug.",
  inputSchema: {
    identifier: z2.string().trim().min(3).describe("Report UUID, display id (e.g. CAI-2026-00000123), or public share slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ identifier }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(identifier);
    const col = uuid ? "id" : identifier.startsWith("CAI-") ? "display_id" : "slug";
    const { data, error } = await client2(ctx).from("reports").select("*").eq(col, identifier).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Report not found or access denied." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { report: data }
    };
  }
});

// src/lib/mcp/tools/list-comments.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_comments_default = defineTool3({
  name: "list_comments",
  title: "List comments",
  description: "List comments on a Concept AI report (by report UUID). Requires access to the report.",
  inputSchema: {
    reportId: z3.string().uuid().describe("Report UUID."),
    limit: z3.number().int().min(1).max(100).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ reportId, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const { data, error } = await client3(ctx).from("comments").select("id, report_id, user_id, body, created_at").eq("report_id", reportId).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { comments: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "smjiyjenxbtfiiovxbnq";
var mcp_default = defineMcp({
  name: "concept-ai-mcp",
  title: "Concept AI",
  version: "0.1.0",
  instructions: "Tools for Concept AI, an evidence-aware feasibility analysis app. Use list_reports to browse the signed-in user's analyses, get_report to fetch a full FMART-O report (by UUID, CAI display id, or share slug), and list_comments for report discussion.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_reports_default, get_report_default, list_comments_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
