// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list_reports.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function client(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_reports_default = defineTool({
  name: "list_reports",
  title: "List my reports",
  description: "List feasibility reports owned by the signed-in user. Returns id, title, industry, status, verdict, and updated_at, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum reports to return (1-50)."),
    include_archived: z.boolean().default(false).describe("Include soft-archived reports.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, include_archived }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = client(ctx).from("reports").select("id, title, industry, status, updated_at, slug, output").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit);
    if (!include_archived) query = query.is("archived_at", null);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((r) => ({
      id: r.id,
      title: r.title,
      industry: r.industry,
      status: r.status,
      slug: r.slug,
      verdict: r?.output?.verdict?.recommendation ?? r?.output?.recommendation ?? null,
      updated_at: r.updated_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { reports: rows }
    };
  }
});

// src/lib/mcp/tools/get_report.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function client2(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient2(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_report_default = defineTool2({
  name: "get_report",
  title: "Get a report",
  description: "Fetch a full feasibility report (inputs, analysis output, verdict) by report id or slug. Only returns reports the signed-in user can access.",
  inputSchema: {
    id: z2.string().optional().describe("Report UUID."),
    slug: z2.string().optional().describe("Public share slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!id && !slug) {
      return { content: [{ type: "text", text: "Provide id or slug" }], isError: true };
    }
    const sb = client2(ctx);
    const q = sb.from("reports").select("*");
    const { data, error } = id ? await q.eq("id", id).maybeSingle() : await q.eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Report not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { report: data }
    };
  }
});

// src/lib/mcp/tools/list_comments.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function client3(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient3(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_comments_default = defineTool3({
  name: "list_comments",
  title: "List comments on a report",
  description: "List all comments on a report the signed-in user can access.",
  inputSchema: {
    report_id: z3.string().uuid().describe("Report UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ report_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client3(ctx).from("report_comments").select("id, body, section, user_id, created_at").eq("report_id", report_id).order("created_at", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { comments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add_comment.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
function client4(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient4(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_comment_default = defineTool4({
  name: "add_comment",
  title: "Add a comment to a report",
  description: "Post a new comment on a report as the signed-in user.",
  inputSchema: {
    report_id: z4.string().uuid().describe("Report UUID."),
    body: z4.string().min(1).max(4e3).describe("Comment body (plain text or markdown)."),
    section: z4.string().max(80).optional().describe("Optional section identifier the comment refers to.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ report_id, body, section }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client4(ctx).from("report_comments").insert({ report_id, body, section: section ?? null, user_id: ctx.getUserId() }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Comment ${data?.id} added.` }],
      structuredContent: { comment: data }
    };
  }
});

// src/lib/mcp/tools/set_report_status.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
function client5(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient5(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var set_report_status_default = defineTool5({
  name: "set_report_status",
  title: "Change a report's status",
  description: "Update the decision status of a report the signed-in user owns. Allowed statuses: draft, in_review, approved, rejected, archived.",
  inputSchema: {
    report_id: z5.string().uuid().describe("Report UUID."),
    status: z5.enum(["draft", "in_review", "approved", "rejected", "archived"]).describe("New status."),
    note: z5.string().max(500).optional().describe("Optional note recorded in status history.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ report_id, status, note }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = client5(ctx);
    const { data: current } = await sb.from("reports").select("id, status, user_id").eq("id", report_id).maybeSingle();
    if (!current) return { content: [{ type: "text", text: "Report not found or not accessible." }], isError: true };
    if (current.user_id !== ctx.getUserId()) {
      return { content: [{ type: "text", text: "Only the report owner can change status." }], isError: true };
    }
    const from_status = current.status;
    const { error: updErr } = await sb.from("reports").update({ status }).eq("id", report_id);
    if (updErr) return { content: [{ type: "text", text: updErr.message }], isError: true };
    await sb.from("report_status_history").insert({
      report_id,
      from_status,
      to_status: status,
      note: note ?? null,
      changed_by: ctx.getUserId()
    });
    return {
      content: [{ type: "text", text: `Status updated from ${from_status} to ${status}.` }],
      structuredContent: { report_id, from_status, to_status: status }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "smjiyjenxbtfiiovxbnq";
var mcp_default = defineMcp({
  name: "concept-ai-mcp",
  title: "Concept AI",
  version: "0.1.0",
  instructions: "Tools for Concept AI (FMART-O feasibility analysis). Use list_reports to browse the user's reports, get_report to read one in full, list_comments/add_comment to collaborate, and set_report_status to move a report through draft \u2192 in_review \u2192 approved / rejected / archived.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_reports_default, get_report_default, list_comments_default, add_comment_default, set_report_status_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
