// This file is automatically generated. Keep the schema overlay import so
// application RPC types stay aligned with forward-only hardening migrations.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './schema';
import { createSchemaCompatibleFetch } from '../../lib/supabaseFetchCompat';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: createSchemaCompatibleFetch(),
  },
});
