// This file is automatically generated. Do not edit it directly.
import { createClient, type SupportedStorage } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!isSupabaseConfigured) {
  console.error('Missing Supabase environment variables. Check VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.');
}

const memoryStorage = new Map<string, string>();

const safeStorage: SupportedStorage = {
  getItem: (key: string) => {
    try {
      return localStorage.getItem(key) ?? memoryStorage.get(key) ?? null;
    } catch {
      return memoryStorage.get(key) ?? null;
    }
  },
  setItem: (key: string, value: string) => {
    memoryStorage.set(key, value);
    try {
      localStorage.setItem(key, value);
    } catch {
      // Storage can be unavailable in private or embedded browsers.
    }
  },
  removeItem: (key: string) => {
    memoryStorage.delete(key);
    try {
      localStorage.removeItem(key);
    } catch {
      // Storage can be unavailable in private or embedded browsers.
    }
  },
};

// Keep the app renderable even if Lovable/Supabase env vars are missing.
// Auth and data calls are disabled by isSupabaseConfigured checks in providers/pages.
const safeSupabaseUrl = SUPABASE_URL || 'https://placeholder.supabase.co';
const safeSupabaseKey = SUPABASE_PUBLISHABLE_KEY || 'placeholder-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(safeSupabaseUrl, safeSupabaseKey, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});